name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: 1. 拉取指定稳定版本的代码
        uses: actions/checkout@v4
        with:
          ref: 'dev_v1.11.7'

      - name: 2. 配置 Java 环境
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 3. 配置 Flutter 环境
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: 4. 安装项目依赖
        run: |
          cd simple_live_app
          flutter pub get

      - name: 5. 编译 iOS 手机端程序
        run: |
          cd simple_live_app
          flutter build ios --release --no-codesign

      - name: 6. 打包为 IPA 文件
        run: |
          cd simple_live_app/build/ios/iphoneos
          mkdir Payload
          mv Runner.app Payload/
          zip -qr SimpleLive-Mobile.ipa Payload/

      - name: 7. 上传 IPA 供下载
        uses: actions/upload-artifact@v4
        with:
          name: SimpleLive-iOS-Mobile-App
          path: simple_live_app/build/ios/iphoneos/SimpleLive-Mobile.ipa
